  name: Build and Deploy
   
  on:
    workflow_dispatch:
      branches:
        - main

  jobs:
    build-deploy:
      name: Build and Deploy Spring Boot API
      runs-on: ubuntu-latest
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      steps:
        - name: Read secrects
          run: echo "USERNAME and PASSWORD values in the dev job is $USERNAME and $PASSWORD"
          
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: 17
            distribution: 'temurin'

        - name: Run unit tests
          run: mvn -B test --file pom.xml
          
        - name: Build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml
            
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ env.USERNAME }}
            password: ${{ env.PASSWORD }}            
          
        - name: Build and Push the docker image
          uses: docker/build-push-action@v5.1.0
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-api:latest
