  name: Build and Deploy
  on:
    workflow_dispatch:
      branches:
        - main

  jobs:
    build-deploy:
      name: Build and Deploy Spring Boot API
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'

        - name: Run unit tests
          run: mvn -B test --file pom.xml
          
        - name: Build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml
            
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}            
          
        - name: Build and Push the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-api:latest
